//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Local_Producto = new HashSet<Local_Producto>();
            this.Producto_Usuario = new HashSet<Producto_Usuario>();
        }
    
        public int Id_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public string Categoria_Producto { get; set; }
        public decimal Precio_Producto { get; set; }
        public Nullable<int> Id_Carrito { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local_Producto> Local_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Usuario> Producto_Usuario { get; set; }
    }
}
