//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Usuario
    {
        public int Id { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Usuario { get; set; }
        public Nullable<int> Id_Carrito { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Carrito Carrito { get; set; }
    }
}
