//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Producto_Usuario = new HashSet<Producto_Usuario>();
            this.Usuario_Local = new HashSet<Usuario_Local>();
        }
    
        public int Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Apellido_Paterno_Usuario { get; set; }
        public string Apellido_Materno_Usuario { get; set; }
        public string Correo_Usuario { get; set; }
        public System.DateTime Fecha_Nacimiento_Usuario { get; set; }
        public string Telefono_Usuario { get; set; }
        public string Contrasena_Usuario { get; set; }
        public Nullable<int> Id_Carrito { get; set; }
    
        public virtual Carrito Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Usuario> Producto_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Local> Usuario_Local { get; set; }
    }
}
